import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";

export interface HandoverPackProps {
  pkg: any;
  project: any;
  documents: any[];
  inspections: any[];
  issues: any[];
  approvals: any[];
  activity: any[];
  generatedBy: string;
}

const styles = StyleSheet.create({
  document: { fontSize: 10, fontFamily: "Helvetica" },
  page: { padding: 40, backgroundColor: "#ffffff" },
  pageMargin: { marginBottom: 40 },

  // Cover page
  coverPage: { justifyContent: "space-between" },
  coverTitle: { fontSize: 32, fontWeight: "bold", color: "#4f46e5", marginBottom: 8 },
  coverSubtitle: { fontSize: 12, color: "#6b7280", marginBottom: 40 },
  coverMetadata: { marginBottom: 20, paddingTop: 20, borderTopWidth: 1, borderTopColor: "#e5e7eb" },
  coverField: { flexDirection: "row", marginBottom: 8, fontSize: 11 },
  coverLabel: { fontWeight: "bold", color: "#111827", width: 120 },
  coverValue: { color: "#374151", flex: 1 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4, marginBottom: 20, width: 100 },

  // Headings
  sectionHeading: {
    backgroundColor: "#4f46e5",
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "bold",
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginBottom: 12,
    marginTop: 16,
  },

  // Tables
  table: { marginBottom: 16 },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#e5e7eb", paddingVertical: 8 },
  tableHeader: { backgroundColor: "#f3f4f6", fontWeight: "bold", paddingVertical: 8 },
  tableCell: { flex: 1, paddingHorizontal: 6, fontSize: 9 },

  // Text
  text: { fontSize: 10, color: "#111827" },
  textMuted: { fontSize: 9, color: "#6b7280" },

  // Footer
  footer: { position: "absolute", bottom: 20, left: 40, right: 40, flexDirection: "row", justifyContent: "space-between", fontSize: 8, color: "#9ca3af", borderTopWidth: 1, borderTopColor: "#e5e7eb", paddingTop: 8 },
});

function statusColor(s: string): string {
  const map: Record<string, string> = {
    "Approved for Use": "#047857",
    Approved: "#047857",
    Passed: "#047857",
    Draft: "#6b7280",
    Open: "#6b7280",
    Submitted: "#1d4ed8",
    "In Progress": "#1d4ed8",
    Superseded: "#9ca3af",
    Failed: "#dc2626",
    Rejected: "#dc2626",
    "Awaiting Approval": "#d97706",
    Pending: "#d97706",
  };
  return map[s] ?? "#6b7280";
}

function CoverPage({ pkg, project, generatedBy }: HandoverPackProps) {
  const today = new Date().toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });

  return (
    <Page size="A4" style={[styles.page, styles.coverPage]}>
      <View>
        <Text style={styles.coverTitle}>{pkg.name}</Text>
        <Text style={styles.coverSubtitle}>Evidence & Handover Pack</Text>

        <View style={[styles.statusBadge, { backgroundColor: statusColor(pkg.status) }]}>
          <Text style={{ color: "#ffffff", fontSize: 10, fontWeight: "bold" }}>
            {pkg.status}
          </Text>
        </View>

        <View style={styles.coverMetadata}>
          <View style={styles.coverField}>
            <Text style={styles.coverLabel}>Package Code</Text>
            <Text style={styles.coverValue}>{pkg.code}</Text>
          </View>
          {project && (
            <>
              <View style={styles.coverField}>
                <Text style={styles.coverLabel}>Project</Text>
                <Text style={styles.coverValue}>{project.name}</Text>
              </View>
              <View style={styles.coverField}>
                <Text style={styles.coverLabel}>Client</Text>
                <Text style={styles.coverValue}>{project.clientName}</Text>
              </View>
              <View style={styles.coverField}>
                <Text style={styles.coverLabel}>Location</Text>
                <Text style={styles.coverValue}>{project.location}</Text>
              </View>
            </>
          )}
          <View style={styles.coverField}>
            <Text style={styles.coverLabel}>Owner</Text>
            <Text style={styles.coverValue}>{pkg.ownerCompany}</Text>
          </View>
          <View style={styles.coverField}>
            <Text style={styles.coverLabel}>Responsible</Text>
            <Text style={styles.coverValue}>{pkg.responsible}</Text>
          </View>
        </View>
      </View>

      <View style={{ borderTopWidth: 1, borderTopColor: "#e5e7eb", paddingTop: 20 }}>
        <Text style={styles.textMuted}>Generated by: {generatedBy}</Text>
        <Text style={styles.textMuted}>{today}</Text>
        <Text style={[styles.textMuted, { marginTop: 16, fontWeight: "bold" }]}>HindTrail</Text>
        <Text style={styles.textMuted}>Project execution across contractors</Text>
      </View>
    </Page>
  );
}

function OverviewPage({ pkg }: HandoverPackProps) {
  return (
    <Page size="A4" style={styles.page}>
      <Text style={styles.sectionHeading}>1. Package Overview</Text>

      <View style={styles.table}>
        <View style={[styles.tableRow, styles.tableHeader]}>
          <Text style={[styles.tableCell, { flex: 1.5 }]}>Field</Text>
          <Text style={styles.tableCell}>Value</Text>
        </View>
        <View style={styles.tableRow}>
          <Text style={[styles.tableCell, { flex: 1.5, fontWeight: "bold" }]}>Status</Text>
          <Text style={styles.tableCell}>{pkg.status}</Text>
        </View>
        <View style={styles.tableRow}>
          <Text style={[styles.tableCell, { flex: 1.5, fontWeight: "bold" }]}>Owner Company</Text>
          <Text style={styles.tableCell}>{pkg.ownerCompany}</Text>
        </View>
        <View style={styles.tableRow}>
          <Text style={[styles.tableCell, { flex: 1.5, fontWeight: "bold" }]}>Responsible</Text>
          <Text style={styles.tableCell}>{pkg.responsible}</Text>
        </View>
        <View style={styles.tableRow}>
          <Text style={[styles.tableCell, { flex: 1.5, fontWeight: "bold" }]}>Due Date</Text>
          <Text style={styles.tableCell}>{pkg.dueDate || "—"}</Text>
        </View>
      </View>

      {pkg.description && (
        <>
          <Text style={[styles.sectionHeading, { marginTop: 20 }]}>Description</Text>
          <Text style={[styles.text, { lineHeight: 1.4 }]}>{pkg.description}</Text>
        </>
      )}
    </Page>
  );
}

function DocumentsPage({ documents }: HandoverPackProps) {
  if (documents.length === 0) return null;

  const current = documents.filter((d) => d.isCurrent);
  const superseded = documents.filter((d) => !d.isCurrent);

  return (
    <Page size="A4" style={styles.page}>
      <Text style={styles.sectionHeading}>2. Documents</Text>

      {current.length > 0 && (
        <View style={styles.table}>
          <Text style={[styles.text, { fontWeight: "bold", marginBottom: 8 }]}>Current Versions</Text>
          <View style={[styles.tableRow, styles.tableHeader]}>
            <Text style={[styles.tableCell, { flex: 2 }]}>Title</Text>
            <Text style={styles.tableCell}>Type</Text>
            <Text style={styles.tableCell}>Revision</Text>
            <Text style={styles.tableCell}>Status</Text>
          </View>
          {current.map((d) => (
            <View key={d.id} style={styles.tableRow}>
              <Text style={[styles.tableCell, { flex: 2 }]}>{d.title}</Text>
              <Text style={styles.tableCell}>{d.type}</Text>
              <Text style={styles.tableCell}>{d.revision}</Text>
              <Text style={[styles.tableCell, { color: statusColor(d.status) }]}>{d.status}</Text>
            </View>
          ))}
        </View>
      )}

      {superseded.length > 0 && (
        <View style={[styles.table, { marginTop: 16 }]}>
          <Text style={[styles.text, { fontWeight: "bold", marginBottom: 8, color: "#6b7280" }]}>Superseded Versions</Text>
          <View style={[styles.tableRow, styles.tableHeader, { backgroundColor: "#f9fafb" }]}>
            <Text style={[styles.tableCell, { flex: 2 }]}>Title</Text>
            <Text style={styles.tableCell}>Revision</Text>
            <Text style={styles.tableCell}>Date</Text>
          </View>
          {superseded.map((d) => (
            <View key={d.id} style={[styles.tableRow, { opacity: 0.6 }]}>
              <Text style={[styles.tableCell, { flex: 2 }]}>{d.title}</Text>
              <Text style={styles.tableCell}>{d.revision}</Text>
              <Text style={styles.tableCell}>{d.uploadDate}</Text>
            </View>
          ))}
        </View>
      )}
    </Page>
  );
}

function InspectionsPage({ inspections }: HandoverPackProps) {
  if (inspections.length === 0) return null;

  return (
    <Page size="A4" style={styles.page}>
      <Text style={styles.sectionHeading}>3. Inspections</Text>

      <View style={styles.table}>
        <View style={[styles.tableRow, styles.tableHeader]}>
          <Text style={styles.tableCell}>Type</Text>
          <Text style={styles.tableCell}>Date</Text>
          <Text style={styles.tableCell}>Inspector</Text>
          <Text style={styles.tableCell}>Result</Text>
        </View>
        {inspections.map((i) => (
          <View key={i.id} style={styles.tableRow}>
            <Text style={styles.tableCell}>{i.type}</Text>
            <Text style={styles.tableCell}>{i.date}</Text>
            <Text style={styles.tableCell}>{i.inspector}</Text>
            <Text style={[styles.tableCell, { color: statusColor(i.result), fontWeight: "bold" }]}>
              {i.result}
            </Text>
          </View>
        ))}
      </View>
    </Page>
  );
}

function IssuesPage({ issues }: HandoverPackProps) {
  if (issues.length === 0) return null;

  return (
    <Page size="A4" style={styles.page}>
      <Text style={styles.sectionHeading}>4. Issues</Text>

      <View style={styles.table}>
        <View style={[styles.tableRow, styles.tableHeader]}>
          <Text style={[styles.tableCell, { flex: 2 }]}>Title</Text>
          <Text style={styles.tableCell}>Severity</Text>
          <Text style={styles.tableCell}>Status</Text>
          <Text style={styles.tableCell}>Owner</Text>
        </View>
        {issues.map((iss) => (
          <View key={iss.id} style={styles.tableRow}>
            <Text style={[styles.tableCell, { flex: 2 }]}>{iss.title}</Text>
            <Text style={styles.tableCell}>{iss.severity}</Text>
            <Text style={[styles.tableCell, { color: statusColor(iss.status) }]}>{iss.status}</Text>
            <Text style={styles.tableCell}>{iss.owner}</Text>
          </View>
        ))}
      </View>
    </Page>
  );
}

function ApprovalsPage({ approvals }: HandoverPackProps) {
  if (approvals.length === 0) return null;

  return (
    <Page size="A4" style={styles.page}>
      <Text style={styles.sectionHeading}>5. Approvals</Text>

      <View style={styles.table}>
        <View style={[styles.tableRow, styles.tableHeader]}>
          <Text style={[styles.tableCell, { flex: 1.5 }]}>Object</Text>
          <Text style={styles.tableCell}>Approver</Text>
          <Text style={styles.tableCell}>Decision</Text>
          <Text style={styles.tableCell}>Date</Text>
        </View>
        {approvals.map((a) => (
          <View key={a.id} style={styles.tableRow}>
            <Text style={[styles.tableCell, { flex: 1.5 }]}>{a.objectLabel}</Text>
            <Text style={styles.tableCell}>{a.approver}</Text>
            <Text style={[styles.tableCell, { color: statusColor(a.decision), fontWeight: "bold" }]}>
              {a.decision}
            </Text>
            <Text style={styles.tableCell}>{a.decisionDate || "—"}</Text>
          </View>
        ))}
      </View>
    </Page>
  );
}

function ActivityPage({ activity }: HandoverPackProps) {
  return (
    <Page size="A4" style={styles.page}>
      <Text style={styles.sectionHeading}>6. Audit Trail</Text>

      {activity.length === 0 ? (
        <Text style={styles.textMuted}>No activity recorded</Text>
      ) : (
        activity.map((a, idx) => (
          <View key={a.id || idx} style={{ marginBottom: 12 }}>
            <View style={{ flexDirection: "row" }}>
              <Text style={[styles.textMuted, { width: 80 }]}>
                {new Date(a.timestamp).toLocaleDateString()}
              </Text>
              <View style={{ flex: 1 }}>
                <Text style={styles.text}>
                  <Text style={{ fontWeight: "bold" }}>{a.user}</Text> ({a.company})
                </Text>
                <Text style={styles.text}>
                  {a.actionType} {a.objectType}
                </Text>
                <Text style={styles.textMuted}>{a.objectLabel}</Text>
              </View>
            </View>
          </View>
        ))
      )}
    </Page>
  );
}

export function HandoverPackPDF(props: HandoverPackProps) {
  return (
    <Document>
      <CoverPage {...props} />
      <OverviewPage {...props} />
      <DocumentsPage {...props} />
      <InspectionsPage {...props} />
      <IssuesPage {...props} />
      <ApprovalsPage {...props} />
      <ActivityPage {...props} />
    </Document>
  );
}
